USE [master]
GO

/****** Object:  Database [tpcc_bp]    Script Date: 10/8/2021 8:08:13 AM ******/
CREATE DATABASE [tpcc_bp]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'tpcc-e-1', FILENAME = N'E:\tpcc-e-1.mdf' , SIZE = 33554432KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
( NAME = N'tpcc-e-2', FILENAME = N'E:\tpcc-e-2.mdf' , SIZE = 33554432KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
( NAME = N'tpcc-f-1', FILENAME = N'F:\tpcc-f-1.mdf' , SIZE = 33554432KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
( NAME = N'tpcc-f-2', FILENAME = N'F:\tpcc-f-2.mdf' , SIZE = 33554432KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'tpcc_log', FILENAME = N'I:\tpcc_log.ldf' , SIZE = 102400KB , MAXSIZE = 48GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tpcc_bp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tpcc_bp] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [tpcc_bp] SET ANSI_NULLS OFF
GO

ALTER DATABASE [tpcc_bp] SET ANSI_PADDING OFF
GO

ALTER DATABASE [tpcc_bp] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [tpcc_bp] SET ARITHABORT OFF
GO

ALTER DATABASE [tpcc_bp] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [tpcc_bp] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [tpcc_bp] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [tpcc_bp] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [tpcc_bp] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [tpcc_bp] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [tpcc_bp] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [tpcc_bp] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [tpcc_bp] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [tpcc_bp] SET  DISABLE_BROKER
GO

ALTER DATABASE [tpcc_bp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [tpcc_bp] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [tpcc_bp] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [tpcc_bp] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [tpcc_bp] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [tpcc_bp] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [tpcc_bp] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [tpcc_bp] SET RECOVERY SIMPLE
GO

ALTER DATABASE [tpcc_bp] SET  MULTI_USER
GO

ALTER DATABASE [tpcc_bp] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [tpcc_bp] SET DB_CHAINING OFF
GO

ALTER DATABASE [tpcc_bp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [tpcc_bp] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [tpcc_bp] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [tpcc_bp] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

ALTER DATABASE [tpcc_bp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [tpcc_bp] SET  READ_WRITE
GO


