USE [*DBNAME*]
DROP TABLE [dbo]. [CUSTOMER]
DROP TABLE [dbo]. [DISTRICT]
DROP TABLE [dbo]. [HISTORY]
DROP TABLE [dbo]. [ITEM]
DROP TABLE [dbo]. [NEW_ORDER]
DROP TABLE [dbo]. [ORDER_LINE]
DROP TABLE [dbo]. [ORDERS]
DROP TABLE [dbo]. [STOCK]
DROP TABLE [dbo]. [WAREHOUSE]
GO


USE [*DBNAME*]
DROP PROCEDURE [dbo]. [DELIVERY]
DROP PROCEDURE [dbo]. [NEWORD]
DROP PROCEDURE [dbo]. [OSTAT]
DROP PROCEDURE [dbo]. [PAYMENT]
DROP PROCEDURE [dbo]. [SLEV]
GO
